/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_iubo_youboauth_testjni_JniUtils */

#ifndef _Included_cn_iubo_youboauth_testjni_JniUtils
#define _Included_cn_iubo_youboauth_testjni_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_iubo_youboauth_testjni_JniUtils
 * Method:    getJniString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_iubo_youboauth_testjni_JniUtils_getJniString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
